<?php

$customerChatboxHelperData = $this->helper('Shop\CustomerChatbox\Helper\Data');
?>
<!-- Facebook Messenger -->
<?php if ($customerChatboxHelperData->getFacebookMessengerStatus()): ?>
<script>
	 window.fbAsyncInit = function() {
          FB.init({
            xfbml            : true,
            version          : 'v6.0'
          });
        };
    (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = 'https://connect.facebook.net/<?= $block->getLocate(); ?>/sdk/xfbml.customerchat.js';
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>
<!-- Your customer chat code -->
<?= $customerChatboxHelperData->getFacebookMessengerChatCode(); ?>
<?php endif; ?>
<!-- End Facebook Messenger -->
<!-- Load Facebook SDK for JavaScript -->
     
    